version: '3.8'

services:
  ms-auth:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/ms_auth_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=sasa
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: ms_auth_db
      MYSQL_PASSWORD: sasa
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
